// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhalletRoute.Infrastructure.Persistence;

#nullable disable

namespace WhalletRoute.Infrastructure.Migrations
{
    [DbContext(typeof(WhalletRouteDbContext))]
    [Migration("20260722182237_SyncDomainColumns")]
    partial class SyncDomainColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhalletRoute.Domain.Deliveries.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("WhalletRoute.Domain.Fleet.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Document")
                        .HasColumnType("text");

                    b.Property<string>("LicenseCategory")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("LicenseExpiry")
                        .HasColumnType("date");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("WhalletRoute.Domain.Fleet.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapacityKg")
                        .HasColumnType("double precision");

                    b.Property<double>("CapacityM3")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("WhalletRoute.Domain.Tenancy.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("WhalletRoute.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("WhalletRoute.Domain.Deliveries.Cargo", b =>
                {
                    b.OwnsOne("WhalletRoute.Domain.Geo.Coordinate", "OriginCoordinate", b1 =>
                        {
                            b1.Property<Guid>("CargoId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("origin_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("origin_longitude");

                            b1.HasKey("CargoId");

                            b1.ToTable("cargos");

                            b1.WithOwner()
                                .HasForeignKey("CargoId");
                        });

                    b.OwnsMany("WhalletRoute.Domain.Deliveries.Delivery", "Deliveries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("CargoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ClientName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Instructions")
                                .HasColumnType("text");

                            b1.Property<int?>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("VolumeM3")
                                .HasColumnType("double precision");

                            b1.Property<double>("WeightKg")
                                .HasColumnType("double precision");

                            b1.HasKey("Id");

                            b1.HasIndex("CargoId");

                            b1.ToTable("deliveries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CargoId");

                            b1.OwnsOne("WhalletRoute.Domain.Geo.Coordinate", "Coordinate", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("longitude");

                                    b2.HasKey("DeliveryId");

                                    b2.ToTable("deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryId");
                                });

                            b1.OwnsOne("WhalletRoute.Domain.Deliveries.DeliveryWindow", "Window", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly>("From")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("window_from");

                                    b2.Property<TimeOnly>("To")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("window_to");

                                    b2.HasKey("DeliveryId");

                                    b2.ToTable("deliveries");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryId");
                                });

                            b1.OwnsMany("WhalletRoute.Domain.Deliveries.StatusChange", "History", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Note")
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("OccurredAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("To")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DeliveryId", "Id");

                                    b2.ToTable("delivery_status_history", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryId");

                                    b2.OwnsOne("WhalletRoute.Domain.Geo.Coordinate", "Location", b3 =>
                                        {
                                            b3.Property<Guid>("StatusChangeDeliveryId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("StatusChangeId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Latitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("latitude");

                                            b3.Property<double>("Longitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("longitude");

                                            b3.HasKey("StatusChangeDeliveryId", "StatusChangeId");

                                            b3.ToTable("delivery_status_history");

                                            b3.WithOwner()
                                                .HasForeignKey("StatusChangeDeliveryId", "StatusChangeId");
                                        });

                                    b2.Navigation("Location");
                                });

                            b1.Navigation("Coordinate");

                            b1.Navigation("History");

                            b1.Navigation("Window");
                        });

                    b.Navigation("Deliveries");

                    b.Navigation("OriginCoordinate");
                });
#pragma warning restore 612, 618
        }
    }
}
